CREATE TABLE Contact (
	ID SERIAL CONSTRAINT CONTACT_PK PRIMARY KEY, 
	FORENAME VARCHAR,
	LASTNAME VARCHAR,
	EMAIL VARCHAR,
	TEL VARCHAR,
	DESCRIPTION VARCHAR
); ALTER TABLE activity
 ALTER COLUMN id SET DEFAULT nextval('activity_seq'::regclass);