CREATE TABLE ContainerCrane (
	ID SERIAL CONSTRAINT CONTAINER_CRANE_PK PRIMARY KEY, 
	NAME VARCHAR,
	HOIST_POWER INTEGER
); ALTER TABLE activity
 ALTER COLUMN id SET DEFAULT nextval('activity_seq'::regclass);