CREATE TABLE Opportunity (
	ID SERIAL CONSTRAINT OPPORTUNITY_PK PRIMARY KEY, 
	NAME VARCHAR,
	PROBABILITY VARCHAR,
	STATUS VARCHAR
); ALTER TABLE activity
 ALTER COLUMN id SET DEFAULT nextval('activity_seq'::regclass);