CREATE TABLE Port (
	ID SERIAL CONSTRAINT PORT_PK PRIMARY KEY, 
	NAME VARCHAR,
	NUMBER_OF_CONTAINER_CRANES INTEGER
); ALTER TABLE activity
 ALTER COLUMN id SET DEFAULT nextval('activity_seq'::regclass);